#pragma once

#include <return_stats_identity_generated.hpp>

#include <string_view>

namespace pineforge::hpo {

/// True when this build's return-statistics identity is bound to the compile commands that the
/// build system generated for the reducer translation units.
///
/// It is false for builds that cannot be bound exactly: multi-configuration generators,
/// compiler launchers or wrappers, response files, a missing or ambiguous compilation database
/// entry, or a CMake older than 3.19. Such a build compiles and runs as usual, but a caller must
/// refuse to publish return statistics, because no claim-bearing identity exists for them.
constexpr bool return_stats_identity_bound() noexcept {
    return detail::return_stats_identity_generated::kBound;
}

/// Short code naming why the identity is unbound; empty when it is bound.
constexpr std::string_view return_stats_identity_unbound_reason() noexcept {
    return {detail::return_stats_identity_generated::kUnboundReason,
            sizeof(detail::return_stats_identity_generated::kUnboundReason) - 1};
}

/// Contract string that was bound into this build's identity at configure time.
///
/// It is a separate constant from the reducer's own contract constant; a caller that includes
/// both headers should assert that the two are equal.
constexpr std::string_view return_stats_contract() noexcept {
    return {detail::return_stats_identity_generated::kContract,
            sizeof(detail::return_stats_identity_generated::kContract) - 1};
}

/// Opaque identity of the build that computes return statistics; empty when unbound.
///
/// It binds the reducer source digest, the compiler identity and driver bytes, the compile
/// command of each reducer translation unit as generated by the build system, and the contract
/// string. It is the same on every sampler path (grid, random, TPE and candidate lists) and is
/// never derived from, combined with or compared to a sampler checkpoint identity. Equal
/// identities name equal builds; they do not attest that two builds produce equal arithmetic,
/// and they say nothing about other architectures.
constexpr std::string_view return_stats_numeric_build_identity() noexcept {
    return {detail::return_stats_identity_generated::kIdentity,
            sizeof(detail::return_stats_identity_generated::kIdentity) - 1};
}

/// Exact descriptor text that the identity is the SHA-256 digest of.
///
/// The text names every hashed source and header with its digest, the compiler fields and one
/// line per normalized compile-command token. Proof tooling compares it with the compilation
/// database of the build; it is not part of any result. An unbound build carries a short
/// descriptor that names the reason.
constexpr std::string_view return_stats_identity_descriptor() noexcept {
    return {detail::return_stats_identity_generated::kDescriptor,
            sizeof(detail::return_stats_identity_generated::kDescriptor) - 1};
}

/// SHA-256 digest, in lower-case hexadecimal, of the sorted reducer source and header entries;
/// empty when unbound.
constexpr std::string_view return_stats_source_digest() noexcept {
    return {detail::return_stats_identity_generated::kSourceDigest,
            sizeof(detail::return_stats_identity_generated::kSourceDigest) - 1};
}

}  // namespace pineforge::hpo
