#include "sobol_engine.hpp"

#include <pineforge/hpo/error.hpp>

#include <stdexcept>

namespace pineforge::hpo::detail {
namespace {

// Generated by scripts/gen_sobol_table.py from the vendored text table: row i is dimension i + 2.
constexpr SobolTableRow kRows[] = {
#include "sobol_table_joe_kuo_d6_1024.inc"
};
static_assert(sizeof(kRows) / sizeof(kRows[0]) == kSobolTableRows,
              "the generated table must hold the rows for dimensions 2..1024");

[[noreturn]] void invariant(const char* message) {
    throw TypedHpoError<std::out_of_range>("hpo_invariant", {}, message);
}

void require_column(std::size_t column) {
    if (column >= kSobolMaxColumns)
        invariant("Sobol column exceeds the vendored direction-number table");
}

// V_1..V_count of a column. Direction numbers follow the authors' recurrence for the integers
//   m_k = 2 a_1 m_{k-1} ^ 2^2 a_2 m_{k-2} ^ ... ^ 2^(s-1) a_{s-1} m_{k-s+1} ^ 2^s m_{k-s} ^ m_{k-s}
// for k > s, where a_1..a_{s-1} are the bits of the table polynomial from the most significant, and
// V_k = m_k * 2^(64-k). Every m_k is odd and below 2^k, so each term stays below 2^k <= 2^64.
void fill_directions(std::size_t column, unsigned count, std::uint64_t* directions) {
    if (column == 0) {  // dimension 1: every m_k is 1
        for (unsigned k = 1; k <= count; ++k)
            directions[k - 1] = std::uint64_t{1} << (64 - k);
        return;
    }
    const SobolTableRow& row = sobol_table_row(column + 1);
    const unsigned degree = row.degree;
    std::uint64_t m[64] = {};
    for (unsigned k = 1; k <= count; ++k) {
        std::uint64_t value;
        if (k <= degree) {
            value = row.initial[k - 1];
        } else {
            const std::uint64_t base = m[k - degree - 1];
            value = (base << degree) ^ base;
            for (unsigned j = 1; j < degree; ++j)
                if (((row.polynomial >> (degree - 1 - j)) & 1u) != 0)
                    value ^= m[k - j - 1] << j;
        }
        m[k - 1] = value;
        directions[k - 1] = value << (64 - k);
    }
}

}  // namespace

const SobolTableRow& sobol_table_row(std::size_t dimension) {
    if (dimension < 2 || dimension > kSobolMaxColumns)
        invariant("Sobol dimension outside the vendored table rows 2..1024");
    return kRows[dimension - 2];
}

SobolDirections64 sobol_directions64(std::size_t column) {
    require_column(column);
    SobolDirections64 directions{};
    fill_directions(column, 64, directions.data());
    return directions;
}

std::uint64_t sobol_shift64(std::uint64_t seed, std::size_t column) {
    require_column(column);
    // SplitMix64 output number column + 1; the state step wraps modulo 2^64 by design.
    std::uint64_t z = seed + (static_cast<std::uint64_t>(column) + 1) * 0x9e3779b97f4a7c15ULL;
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

std::uint64_t sobol_coordinate64(std::uint64_t index,
                                 std::size_t column,
                                 std::uint64_t seed,
                                 SobolScramble scramble) {
    require_column(column);
    if (scramble != SobolScramble::None && scramble != SobolScramble::DigitalShift)
        invariant("invalid Sobol scramble mode");
    // The highest set bit of the Gray code n ^ (n >> 1) is that of n, so only V_1..V_width matter.
    unsigned width = 0;
    for (std::uint64_t rest = index; rest != 0; rest >>= 1)
        ++width;
    std::uint64_t directions[64] = {};
    fill_directions(column, width, directions);
    std::uint64_t gray = index ^ (index >> 1);
    std::uint64_t point = 0;
    for (unsigned k = 0; gray != 0; ++k, gray >>= 1)
        if ((gray & 1u) != 0)
            point ^= directions[k];
    if (scramble == SobolScramble::DigitalShift)
        point ^= sobol_shift64(seed, column);
    return point;
}

}  // namespace pineforge::hpo::detail
